x-app: &app
  build:
    context: ./
    dockerfile: Dockerfile
    network: host
    args:
      USER_UID: "${UID:-1000}"
      USER_GID: "${GID:-100}"
  network_mode: host
  environment: &env
    APP_HOST: rails
  image: berlin:latest
  user: dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - ~/.ssh/:/home/dev/.ssh/:ro
  environment:
    <<: *env
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
  depends_on:
    - postgres

services:
  runner:
    <<: *backend
    command: /bin/bash
    # Inline command in this service doesn't catch SIGTERM to stop so we have to send directly a SIGKILL
    stop_signal: SIGKILL
    environment:
      <<: *env
  rails:
    <<: *backend
    entrypoint: ./entrypoint.sh
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  bundle:
  rails_cache:
  postgres:
